# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:16-alpine 
# Copy app files
COPY ./verifierapp /home/
# Set the working directory to /home inside the container
WORKDIR /home
# ==== BUILD =====
# Install the same version of npm
RUN npm install -g npm@9.6.7
# ==== RUN =======
# Set the env to "production"
ENV NODE_ENV production
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
