version: '3'
services:

  issuerWaltIdIdp:
    image: waltid/idpkit
    ports:
      - 19051:8080
    restart: no
    networks:
      network:
        ipv4_address: 10.5.0.7
    entrypoint: /app/bin/waltid-idpkit run
    volumes:
      - './issuerData/waltId/IDP/data/:/app/data'
      - './issuerData/waltId/IDP/config/:/app/config'

  issuerWaltIdSsi:
    image: waltid/ssikit
    ports:
      - "19011:7001"
      - "19021:7002"
      - "19041:7010"
    restart: no
    entrypoint: /app/bin/waltid-ssikit serve -b 0.0.0.0
    volumes:
      - './issuerData/waltId/SSI/data/:/app/data'
    networks:
      network:
        ipv4_address: 10.5.0.3
    
  walletWaltIdSsi:
    image: waltid/ssikit
    ports:
      - "19020:7002"
    restart: no
    entrypoint: /app/bin/waltid-ssikit serve -b 0.0.0.0
    volumes:
      - './walletData/waltId/SSI/data/:/app/data'
    networks:
      network:
        ipv4_address: 10.5.0.2

  verifierWaltIdSsi:
    image: waltid/ssikit
    ports:
      - "19032:7003"
      - "19022:7002"
    restart: "no"
    entrypoint: /app/bin/waltid-ssikit serve -b 0.0.0.0
    volumes:
      - './verifierData/waltId/SSI/data/:/app/data'
    networks:
      network:
        ipv4_address: 10.5.0.4

  dbIssuerApp:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: issuerapp
    networks:
      network:
        ipv4_address: 10.5.0.5
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8080:8080
    networks:
      network:
        ipv4_address: 10.5.0.6

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
volumes:
  db_data: {}