--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3 (Debian 15.3-1.pgdg120+1)
-- Dumped by pg_dump version 15.3 (Debian 15.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: gender; Type: TYPE; Schema: public; Owner: admin
--

CREATE TYPE public.gender AS ENUM (
    'M',
    'F'
);


ALTER TYPE public.gender OWNER TO admin;

--
-- Name: marital_status; Type: TYPE; Schema: public; Owner: admin
--

CREATE TYPE public.marital_status AS ENUM (
    'married',
    'cohabitant',
    'divorced',
    'widower',
    'separate',
    'canceled',
    'other'
);


ALTER TYPE public.marital_status OWNER TO admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.accounts (
    id integer NOT NULL,
    email character varying NOT NULL,
    hashed_pass character varying(128) NOT NULL,
    salt character varying(32) NOT NULL
);


ALTER TABLE public.accounts OWNER TO admin;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sys_admins; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.sys_admins (
    account integer NOT NULL,
    role character varying NOT NULL
);


ALTER TABLE public.sys_admins OWNER TO admin;

--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    account integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: vcs_content_marital_status; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.vcs_content_marital_status (
    vcs_request integer NOT NULL,
    status public.marital_status NOT NULL,
    "personalIdentifier" character varying NOT NULL
);


ALTER TABLE public.vcs_content_marital_status OWNER TO admin;

--
-- Name: vcs_content_pid; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.vcs_content_pid (
    vcs_request integer NOT NULL,
    "currentAddress" character varying NOT NULL,
    "dateOfBirth" character varying NOT NULL,
    "familyName" character varying NOT NULL,
    "firstName" character varying NOT NULL,
    gender public.gender NOT NULL,
    "nameAndFamilyNameAtBirth" character varying NOT NULL,
    "personalIdentifier" character varying NOT NULL,
    "placeOfBirth" character varying NOT NULL
);


ALTER TABLE public.vcs_content_pid OWNER TO admin;

--
-- Name: vcs_requests; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.vcs_requests (
    id integer NOT NULL,
    applicant integer NOT NULL,
    released boolean DEFAULT false NOT NULL
);


ALTER TABLE public.vcs_requests OWNER TO admin;

--
-- Name: vcs_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.vcs_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vcs_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vcs_requests_verifications; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.vcs_requests_verifications (
    vcs_request integer NOT NULL,
    admin_verifier integer NOT NULL,
    status boolean NOT NULL
);


ALTER TABLE public.vcs_requests_verifications OWNER TO admin;

--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.accounts (id, email, hashed_pass, salt) FROM stdin;
26	admin23@gmail.com	3d70867ca1cf9c2a0bf572ae969a58bc26c4843d48fea461edda0eb98e3dc0808e78f8ef8f0a6c77f5ded43f52e4deda2879e3ee1f9c93cd906f848e62452ab1	df6352acd33cd1873674ca299646abb5
\.


--
-- Data for Name: sys_admins; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.sys_admins (account, role) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (account, created_at) FROM stdin;
\.


--
-- Data for Name: vcs_content_marital_status; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.vcs_content_marital_status (vcs_request, status, "personalIdentifier") FROM stdin;
\.


--
-- Data for Name: vcs_content_pid; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.vcs_content_pid (vcs_request, "currentAddress", "dateOfBirth", "familyName", "firstName", gender, "nameAndFamilyNameAtBirth", "personalIdentifier", "placeOfBirth") FROM stdin;
\.


--
-- Data for Name: vcs_requests; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.vcs_requests (id, applicant, released) FROM stdin;
\.


--
-- Data for Name: vcs_requests_verifications; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.vcs_requests_verifications (vcs_request, admin_verifier, status) FROM stdin;
\.


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.accounts_id_seq', 26, true);


--
-- Name: vcs_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.vcs_requests_id_seq', 49, true);


--
-- Name: accounts accounts_email_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_email_key UNIQUE (email);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: sys_admins sys_admins_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sys_admins
    ADD CONSTRAINT sys_admins_pkey PRIMARY KEY (account);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (account);


--
-- Name: vcs_content_marital_status vcs_content_marital_status_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_content_marital_status
    ADD CONSTRAINT vcs_content_marital_status_pkey PRIMARY KEY (vcs_request);


--
-- Name: vcs_content_pid vcs_content_pid_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_content_pid
    ADD CONSTRAINT vcs_content_pid_pkey PRIMARY KEY (vcs_request);


--
-- Name: vcs_requests vcs_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_requests
    ADD CONSTRAINT vcs_requests_pkey PRIMARY KEY (id);


--
-- Name: vcs_requests_verifications vcs_requests_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_requests_verifications
    ADD CONSTRAINT vcs_requests_verifications_pkey PRIMARY KEY (vcs_request);


--
-- Name: sys_admins sys_admins_account_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sys_admins
    ADD CONSTRAINT sys_admins_account_fkey FOREIGN KEY (account) REFERENCES public.accounts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: users users_account_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_account_fkey FOREIGN KEY (account) REFERENCES public.accounts(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vcs_content_marital_status vcs_content_marital_status_vcs_request_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_content_marital_status
    ADD CONSTRAINT vcs_content_marital_status_vcs_request_fkey FOREIGN KEY (vcs_request) REFERENCES public.vcs_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vcs_content_pid vcs_content_pid_vcs_request_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_content_pid
    ADD CONSTRAINT vcs_content_pid_vcs_request_fkey FOREIGN KEY (vcs_request) REFERENCES public.vcs_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vcs_requests vcs_requests_applicant_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_requests
    ADD CONSTRAINT vcs_requests_applicant_fkey FOREIGN KEY (applicant) REFERENCES public.users(account) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vcs_requests_verifications vcs_requests_verifications_admin_verifier_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_requests_verifications
    ADD CONSTRAINT vcs_requests_verifications_admin_verifier_fkey FOREIGN KEY (admin_verifier) REFERENCES public.sys_admins(account) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: vcs_requests_verifications vcs_requests_verifications_vcs_request_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.vcs_requests_verifications
    ADD CONSTRAINT vcs_requests_verifications_vcs_request_fkey FOREIGN KEY (vcs_request) REFERENCES public.vcs_requests(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

